run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - sqlclosecheck
    - dupl
    - gocyclo
    - goconst
    - contextcheck

  issues:
    max-issues-per-linter: 50
    max-same-issues: 3
    new: false
    fix: false
    uniq-by-line: true
    whole-files: false

linters-settings:
  gofmt:
    simplify: true
